// <auto-generated />
using System;
using JOTrain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JOTrain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829093157_SeedSampleData")]
    partial class SeedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JOTrain.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Irbid"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aqaba"
                        });
                });

            modelBuilder.Entity("JOTrain.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentVia")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("JOTrain.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalStationId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceEconomy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceEconomyPlus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceVIP")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalStationId");

                    b.HasIndex("DepartureStationId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalStationId = 2,
                            DepartureStationId = 1,
                            DepartureTime = new DateTime(2026, 9, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            PriceEconomy = 2.00m,
                            PriceEconomyPlus = 3.50m,
                            PriceVIP = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            ArrivalStationId = 3,
                            DepartureStationId = 1,
                            DepartureTime = new DateTime(2026, 9, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PriceEconomy = 4.00m,
                            PriceEconomyPlus = 6.00m,
                            PriceVIP = 8.00m
                        },
                        new
                        {
                            Id = 3,
                            ArrivalStationId = 4,
                            DepartureStationId = 1,
                            DepartureTime = new DateTime(2026, 9, 12, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            PriceEconomy = 10.00m,
                            PriceEconomyPlus = 15.00m,
                            PriceVIP = 25.00m
                        });
                });

            modelBuilder.Entity("JOTrain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@jotrain.com",
                            FullName = "System Admin",
                            Password = "123",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "staff@jotrain.com",
                            FullName = "Station Staff",
                            Password = "123",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "hamzeh@jotrain.com",
                            FullName = "Hamzeh Waleed Alafaghani",
                            Password = "123",
                            Role = 2
                        });
                });

            modelBuilder.Entity("JOTrain.Models.Ticket", b =>
                {
                    b.HasOne("JOTrain.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JOTrain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOTrain.Models.Trip", b =>
                {
                    b.HasOne("JOTrain.Models.Station", "ArrivalStation")
                        .WithMany()
                        .HasForeignKey("ArrivalStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JOTrain.Models.Station", "DepartureStation")
                        .WithMany()
                        .HasForeignKey("DepartureStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("DepartureStation");
                });
#pragma warning restore 612, 618
        }
    }
}
